"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Mateusz Poliwczak"
email = "mpoliwczak34@gmail.com"

[ui]
conflict-marker-style = "git"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]

[colors]
"diff token" = { underline = false }

[config]
# Set to true to automatically add Gerrit's Change-Id header to commit messages.
# Set per repo via: jj config set --repo config.gerrit_repo true
gerrit_repo = false

[templates]
# https://jj-vcs.github.io/jj/latest/FAQ/#how-do-i-integrate-jujutsu-with-gerrit
commit_trailers = '''
if(
  config("config.gerrit_repo").as_boolean() && !trailers.contains_key("Change-Id"),
  format_gerrit_change_id_trailer(self)
)
'''

# https://github.com/jj-vcs/jj/issues/1946#issuecomment-2572986485
draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.summary()),
  ),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\n",
  "JJ: ignore-rest\n",
  diff.git(),
)
'''
